spring:
  profiles:
    active:
    - dev
---

server:
  port: 3356
spring:
  application:
    name: ksdj
  profiles: dev

---
server:
  port: 3357
spring:
  application:
    name: iou
  profiles: test
